language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
install: python setup.py -q install
# command to run tests
before_script: cd ovf2vtk/Lib/test_ovf2vtk
script: nosetests
