language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
before_install: cd ovf2vtk
install:
 - python setup.py -q install
 - pip install PyVTK
 - pip install coverage
# command to run tests
before_script:
script: make test
