language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
# command to install dependencies
before_install: cd ovf2vtk
cd Lib
cd test_ovf2vtk
install: python setup.py -q install
# command to run tests
script: nosetests
