language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
before_install: cd ovf2vtk
install:
 - python setup.py -q install
 - pip install PyVTK
# command to run tests
before_script: cd Lib/test_ovf2vtk
script: py.test
