language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
# command to install dependencies
script: ovf2vtk\Lib\analysis_tests\all_analysis_tests.py
install: python ovf2vtk\\setup.py -q install
# command to run tests
script: nosetests
